# Basic
title: 郝凡
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: xiaofan
# 头像里面的描述
avatarDesc: 编程爱好者
url: "http://www.91feifan.win/"

# Comment
comment:
    # disqus: xiaofan
    duoshuo: 91feifan 

# Social
social:
    weibo: #
    github: 1151104369
    # twitter: 
    mail: 1151104369@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 4015635e5b362a374cb5df9068941b73  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


